### ISSUE TITLE
Banner too big

### ISSUE THREAD

**Issue by darobin** [w3c/developer-tools#15]
The banner with the logo looks nice, but it takes up half the room above the fold. If this were a site meant to be visited once to get a nice impression, that would be fine, but it's not the use case. The use case is that this is the place you hit as a developer any time you're looking for something at the W3C related to development. You need to get to the content quickly. I think the size should be drastically reduced, even if it's good-looking as is.

**Comment by gbaudusseau** [comment]
I agree. At first the banner contained a search bar. I removed the search bar because our number of tools is too poor.

**Comment by gbaudusseau** [comment]
@darobin, maybe we should keep only the navbar at the top. what do you think?

**Comment by darobin** [comment]
That works for me, but I leave the creative solutions up to you :)

**Comment by gbaudusseau** [comment]
Banner removed.
