### ISSUE TITLE
Add an "Edit on GitHub" button

### ISSUE THREAD

**Issue by astorije** [w3c/developer-tools#19]
The GitHub icon at the top links to all the W3C repositories. I trip on that every time I want to edit that page or repository :-)

It'd be nice to have a button to edit the page(s) similarly to http://docs.ansible.com/playbooks.html.

**Comment by gbaudusseau** [comment]
We can add this link at the top of the page ( in the future header for example #21  ) and also at the bottom just before the copyright.
