### ISSUE TITLE
Merge confusing tool descriptions

### ISSUE THREAD

**Issue by astorije** [w3c/developer-tools#22]
- MobileOK Checker vs Mobile Checker
- Markup Validator vs. Validator.nu

I know these are separate projects maintained by different people, but when you think of the readers of these pages, not aware of the (sometimes political) reasons why these projects are somewhat duplicates, it is confusing.
It'd be better to give a unified description for these with maybe 2 pointers rather than 2 separate items that have roughly the same description.

**Comment by dontcallmedom** [comment]
got rid of markup validator, and the mobile checkers are gone, so closing
