### ISSUE TITLE
public irc channel

### ISSUE THREAD

**Issue by gbaudusseau** [w3c/developer-tools#24]
We want to provide a public irc channel for W3C developer tools.

some ideas:
# w3c-devtools
# devtools
# developer-tools
# w3c-developer-tools

**Comment by darobin** [comment]
I don't think that a channel just for the dev tools will get critical mass. It's not like there are _that_ many. Maybe a channel for developers (`#dev`) instead? Or reuse `#w3c` on Freenode?

**Comment by gbaudusseau** [comment]
#dev on irc.w3.org is the final choice.

**Comment by tripu** [comment]
@guibbs, the page still says `#devtools` in W3C's public IRC server&hellip;

(Anyway, I've been hanging out in `#dev` for the last couple of days, and I've been all alone :¬)
