### ISSUE TITLE
Rendering problems on iOS

### ISSUE THREAD

**Issue by cvrebert** [w3c/developer-tools#33]
https://w3c.github.io/developers/tools.html on iOS 8.3:

The white boxes are borked:
![img_0112](https://cloud.githubusercontent.com/assets/419884/7548481/984c8a04-f5bf-11e4-9721-79dc23fdc962.PNG)

The one button line wraps weirdly:
![img_0111](https://cloud.githubusercontent.com/assets/419884/7548486/ad9096a8-f5bf-11e4-9965-879e2a0c9a72.PNG)

**Comment by gbaudusseau** [comment]
fixed :)

**Comment by cvrebert** [comment]
@guibbs Not entirely:
![img_0114](https://cloud.githubusercontent.com/assets/419884/7758417/58c1456a-ffbe-11e4-9049-36c6959d12fd.PNG)

**Comment by gbaudusseau** [comment]
@cvrebert how is it now? which kind of smartphone are you using? iphone 4?

**Comment by cvrebert** [comment]
Looks good now. iPhone 5S.

**Comment by gbaudusseau** [comment]
Thank you @cvrebert!
